#https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-firebase
steps:
  # Firebase
  - name: 'docker:stable'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/firebase', '.' ]
  # Install
  #- name: 'gcr.io/cloud-builders/npm:current'
  - name: 'node:lts'
    entrypoint: 'npm'
    args: ['install']
  # Test
  #- name: 'gcr.io/cloud-builders/npm:current'
  #- name: 'node:lts'
  # entrypoint: 'npm'
  #  args: ['run', 'test:unit']
  # Build
  #- name: 'gcr.io/cloud-builders/npm:current'
  - name: 'node:lts'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - '_CONFIG=$_CONFIG'
  # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: [ 'deploy', '--project', '$PROJECT_ID', '--token', '$_FIREBASE_TOKEN' ]