import { fileURLToPath, URL } from 'node:url';

import vue from '@vitejs/plugin-vue';

import { defineConfig } from 'vitest/config';

const local = (p) => fileURLToPath(new URL(p, import.meta.url)).replace(/\\/g, '/');

// Separate from vite.config.js on purpose: that file writes src/openSource.js
// and src/config/*.json as a side effect of loading, which a test run must not do.
export default defineConfig({
	// absolute asset URLs (/images/...) are served from public/ at runtime;
	// left alone, the plugin turns them into imports Node cannot resolve
	plugins: [ vue({ template: { transformAssetUrls: { includeAbsolute: false } } }) ],
	resolve: {
		alias: [
			{ find: /^@\//, replacement: local('./src/') },
			// supplied by the build from src/config/<env>.json
			{ find: 'local-config', replacement: local('./test/stubs/config.json') },
			// generated by vite.config.js
			{ find: 'open-source-config', replacement: local('./test/stubs/openSource.js') }
		],
		// as vite.config.js: imports name .vue files without the extension
		extensions: [ '.mjs', '.js', '.json', '.vue' ],
		// resolve packages as the browser build does; decimal.js-light's module
		// build, for one, lacks the Decimal.Decimal its browser build has
		mainFields: [ 'browser', 'module', 'jsnext:main', 'jsnext' ]
	},
	test: {
		environment: 'jsdom',
		// the first import transforms the whole dependency tree, cold
		testTimeout: 30000,
		include: [ 'test/**/*.test.js' ],
		setupFiles: [ 'test/setup.js' ],
		coverage: {
			provider: 'v8',
			reporter: [ 'text-summary', 'lcov' ],
			// every source file, so a file no test loads counts as uncovered
			include: [ 'src/**/*.{js,vue}' ],
			exclude: [
				'src/openSource.js',
				'src/config/**',
				// Vue 2 leftovers nothing imports (see broken in test/modules.test.js);
				// the coverage provider cannot parse them
				'src/components/gameSystems/BoonDialog.vue',
				'src/components/maps/google/**',
				'src/store/index.js'
			],
			// a ratchet, about a point under what was measured on 2026-10-10
			// (statements 12.67, branches 3.93, functions 4.61, lines 13.02);
			// raise these as tests are added, never lower them
			thresholds: { statements: 11, branches: 3, functions: 4, lines: 12 }
		},
		server: {
			deps: {
				// @thzero packages import without file extensions, which Vite resolves
				// but Node does not, so they must be transformed rather than externalized;
				// vuetify ships CSS imports Node cannot load
				inline: [ /@thzero\//, /vuetify/ ]
			}
		}
	}
});
